/*
 * Copyright 2013 - 2016, Freescale Semiconductor, Inc.
 * Copyright 2016-2021 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/*
Static configuration header file for the NXP Touch Library
generated by the NXP Touch GUI Tool
*/
#ifndef NT_SETUP_H
#define NT_SETUP_H

#define SCANTIME 10U

#include "nt.h"

#define NT_XTALK_NSENSORS 44
extern int16_t actMat[NT_XTALK_NSENSORS * NT_XTALK_NSENSORS]; 
/*
extern const struct nt_electrode P1;
extern const struct nt_electrode P2;
extern const struct nt_electrode P3;
extern const struct nt_electrode P4;
extern const struct nt_electrode P5;
extern const struct nt_electrode P6;
extern const struct nt_electrode P7;
extern const struct nt_electrode P8;
extern const struct nt_electrode P9;
extern const struct nt_electrode P10;
*/
extern const struct nt_control Keypad_1;

extern const struct nt_module nt_tsi_module;
extern const struct nt_system System_0;
extern const struct nt_control *const System_0_controls[];
void nt_enable(void);

#endif
