/*
 * Copyright 2022 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);
/*
#define BOARD_LED1_PORT 0U
#define BOARD_LED1_PIN 2U

#define BOARD_LED2_PORT 0U
#define BOARD_LED2_PIN 3U

#define BOARD_LED3_PORT 0U
#define BOARD_LED3_PIN 22U

#define BOARD_LED4_PORT 0U
#define BOARD_LED4_PIN 23U

#define BOARD_LED5_PORT 2U
#define BOARD_LED5_PIN 0U

#define BOARD_LED6_PORT 2U
#define BOARD_LED6_PIN 1U

#define BOARD_LED7_PORT 4U
#define BOARD_LED7_PIN 2U

#define BOARD_LED8_PORT 4U
#define BOARD_LED8_PIN 3U

#define BOARD_LED9_PORT 2U
#define BOARD_LED9_PIN 6U

#define BOARD_LED10_PORT 2U
#define BOARD_LED10_PIN 7U

#define BOARD_LED11_PORT 4U
#define BOARD_LED11_PIN 5U

#define BOARD_LED12_PORT 4U
#define BOARD_LED12_PIN 4U
*/
#define PCR_IBE_ibe0 0x00u /*!<@brief Input Buffer Enable: Disables */
#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PIO0_2 (number 78), led1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_D1_GPIO GPIO0 /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_D1_GPIO_PIN 2U /*!<@brief GPIO pin number */
#define BOARD_LED_D1_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */
/* @} */

/*! @name PIO3_9 (number 69), SLED_STB
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SLED_STB_GPIO GPIO3 /*!<@brief GPIO peripheral base pointer */
#define BOARD_SLED_STB_GPIO_PIN 9U /*!<@brief GPIO pin number */
#define BOARD_SLED_STB_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */
/* @} */

/*! @name PIO3_7 (number 71), SLED_CLK
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SLED_CLK_GPIO GPIO3 /*!<@brief GPIO peripheral base pointer */
#define BOARD_SLED_CLK_GPIO_PIN 7U /*!<@brief GPIO pin number */
#define BOARD_SLED_CLK_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */
/* @} */

/*! @name PIO3_6 (number 72), SLED_DIN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SLED_DIN_GPIO GPIO3 /*!<@brief GPIO peripheral base pointer */
#define BOARD_SLED_DIN_GPIO_PIN 6U /*!<@brief GPIO pin number */
#define BOARD_SLED_DIN_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */
/* @} */

/*! @name TSI0_CH10 (number 82), TOUCH_D1
  @{ */
/* @} */

/*! @name PIO0_3 (number 79), LED_D2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_D2_GPIO GPIO0 /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_D2_GPIO_PIN 3U /*!<@brief GPIO pin number */
#define BOARD_LED_D2_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */
/* @} */

/*! @name TSI0_CH11 (number 84), TOUCH_D1
  @{ */
/* @} */

/*! @name TSI0_CH13 (number 86), TOUCH_D3
  @{ */
/* @} */

/*! @name PIO0_22 (number 90), LED_D3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_D3_GPIO GPIO0 /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_D3_GPIO_PIN 22U /*!<@brief GPIO pin number */
#define BOARD_LED_D3_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */
/* @} */

/*! @name PIO0_23 (number 91), LED_D4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_D4_GPIO GPIO0 /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_D4_GPIO_PIN 23U /*!<@brief GPIO pin number */
#define BOARD_LED_D4_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */
/* @} */

/*! @name PIO2_1 (number 15), LED_D5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_D6_GPIO GPIO2 /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_D6_GPIO_PIN 1U /*!<@brief GPIO pin number */
#define BOARD_LED_D6_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */
/* @} */

/*! @name PIO2_0 (number 14), LED_D5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_D5_GPIO GPIO2 /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_D5_GPIO_PIN 0U /*!<@brief GPIO pin number */
#define BOARD_LED_D5_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */
/* @} */

/*! @name PIO4_2 (number 24), LED_D7
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_D7_GPIO GPIO4 /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_D7_GPIO_PIN 2U /*!<@brief GPIO pin number */
#define BOARD_LED_D7_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */
/* @} */

/*! @name PIO4_3 (number 25), LED_D8
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_D8_GPIO GPIO4 /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_D8_GPIO_PIN 3U /*!<@brief GPIO pin number */
#define BOARD_LED_D8_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */
/* @} */

/*! @name PIO2_7 (number 21), LED_D10
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_D10_GPIO GPIO2 /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_D10_GPIO_PIN 7U /*!<@brief GPIO pin number */
#define BOARD_LED_D10_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */
/* @} */

/*! @name PIO4_5 (number 27), LED_D11
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_D11_GPIO GPIO4 /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_D11_GPIO_PIN 5U /*!<@brief GPIO pin number */
#define BOARD_LED_D11_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */
/* @} */

/*! @name PIO4_4 (number 26), LED_D12
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_D12_GPIO GPIO4 /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_D12_GPIO_PIN 4U /*!<@brief GPIO pin number */
#define BOARD_LED_D12_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */
/* @} */

/*! @name TSI0_CH4 (number 97), TOUCH_D4
  @{ */
/* @} */

/*! @name TSI0_CH5 (number 98), TOUCH_D5
  @{ */
/* @} */

/*! @name TSI0_CH7 (number 100), TOUCH_D6
  @{ */
/* @} */

/*! @name TSI0_CH17 (number 1), TOUCH_D7
  @{ */
/* @} */

/*! @name TSI0_CH19 (number 3), TOUCH_D8
  @{ */
/* @} */

/*! @name TSI0_CH20 (number 4), TOUCH_D9
  @{ */
/* @} */

/*! @name TSI0_CH21 (number 5), TOUCH_D10
  @{ */
/* @} */

/*! @name TSI0_CH22 (number 6), TOUCH_D11
  @{ */
/* @} */

/*! @name TSI0_CH23 (number 7), TOUCH_D12
  @{ */
/* @} */

/*! @name PIO2_6 (number 20), LED_D9
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_D9_GPIO GPIO2 /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_D9_GPIO_PIN 6U /*!<@brief GPIO pin number */
#define BOARD_LED_D9_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
